### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by J0WI**
Moving to GitHub Actions due Travis [policy/pricing changes](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

The CI script is provided by the docker library: https://github.com/docker-library/bashbrew/tree/master/scripts/github-actions

travis.org has recently started to [limit OSS builds](https://www.traviscistatus.com/) resulting in a huge backlog. It will be [closed down completely](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) no later than December 31st, 2020.

### CODE REVIEW

**Comment by J0WI** [comment]
This actually requires a `generate-stackbrew-library.sh` (or any other script that defined in `GENERATE_STACKBREW_LIBRARY`) in the repo generating the [library file](https://github.com/docker-library/official-images/blob/master/library/gradle).

**Comment by keeganwitt** [comment]
Thank you for pointing this out. I'd actually already migrated to Travis.com already because I had issues with builds being triggered on MRs. Given the pricing change, GitHub actions do seem like they'd be more convenient than having to hassle with making sure there are enough credits to keep the builds running.

**Comment by keeganwitt** [comment]
> This actually requires a `generate-stackbrew-library.sh` (or any other script that defined in `GENERATE_STACKBREW_LIBRARY`) in the repo generating the [library file](https://github.com/docker-library/official-images/blob/master/library/gradle).

Yea, I might want to use a simpler configuration than the library example. I'll give it some thought.

**Comment by keeganwitt** [comment]
I opened another MR which is more of a direct replacement for the Travis job (#166).

**Pull request closed without merging**
