### PR TITLE
possible to override UID/GID/UNAME

### PR DESCRIPTION
**Pull request by meltzow**
see here: https://stackoverflow.com/questions/44683119/dockerfile-replicate-the-host-user-uid-and-gid-to-the-image

### CODE REVIEW

**Comment by keeganwitt** [comment]
I don't necessarily object to the idea, but I'm curious; how is this helpful?  Args can only be used when building the image.  Is your use case to fork these Dockerfiles rather than using them as a base image?

**Comment by meltzow** [comment]
hi,
the artefacts created by your docker are owned by your static user and group (in your case always 1000), because the gradle process is running with these user. If I mount some volumes for example in docker-compose.yml files like these: 
```
volumes:
      - ./:/home/
```
to create some artefacts like jars, test-results and so on, they all have the owner 1000, not my own UID. But to work with it I need my own UID.

**Comment by keeganwitt** [comment]
OK. But to be clear, you'd have to clone this repo and build with new args for this to work.  It's not something that can happen at runtime. If this works for your use case, then I'll merge.

**Comment by keeganwitt** [comment]
If the volume is the only problem you're trying to solve with this, you can run it as root in Docker Compose with `user: root`

**Comment by keeganwitt** [comment]
Closing for now, as the use case is unclear.  Feel free to comment with a further explanation to reopen.

**Pull request closed without merging**
