### PR TITLE
add jdk12

### PR DESCRIPTION
**Pull request by davidkarlsen**
Offer jdk12

---
This change is [Reviewable](https://reviewable.io/reviews/keeganwitt/docker-gradle/92)

### CODE REVIEW

**Comment by vvanholl** [comment]
I also forgot package procps

**Comment by vvanholl** [comment]
In reality this is very difficult since jdk12 switched to Oracle Linux in place of Debian

**Comment by vvanholl** [comment]
And I am sure other components could miss :(

**Comment by keeganwitt** [comment]
Are you sure they switched to Oracle Linux?  My interpretation was that there just wasn't a Debian package available yet.  Did you see any announcements on the topic?

**Comment by keeganwitt** [comment]
If you have no objection, I'll close this in favor of #98.  However, if you have a reason you need Oracle Linux, we can consider adding that as well (I mentioned that possibility in #91, though no one has expressed interest so far).

**Comment by davidkarlsen** [comment]
I think I'd stay away from anything with Oracle in its name - you never know when they change the terms and into what - but the track record the later years has been very hostile.

**Pull request closed without merging**
