### PR TITLE
Upgrade Java 14 to 15

### PR DESCRIPTION
**Pull request by keeganwitt**

### CODE REVIEW

**Comment by bric3** [comment]
Great! thank you! I was following adpoptopenjdk 15 publication.
Do you know how long does it usually take for these to be published on the docker hub?

**Comment by keeganwitt** [comment]
If you're asking about AdoptOpenJDK's new images, those are in DockerHub now. If you're asking about my Gradle changes that rely on those changes, from what I've seen, they usually get my MRs merged within a day or two (often the same day). I have seen a couple times where it was longer, but that was fairly rare. After it gets merged, I think it shows up on Hub within an hour, unless there's an issue with their Jenkins builds.

**Comment by bric3** [comment]
@keeganwitt Yes I've been watching adoptopenjdk images. But indeed I'm interested in the gradle images. Thnaks for your feedback and your work.

**Comment by keeganwitt** [comment]
Here's that MR if you want to watch that as well: https://github.com/docker-library/official-images/pull/8916

**Comment by bric3** [comment]
@keeganwitt Ah cool thank you !!

**Pull request merged**
