### PR TITLE
Gradle 8.1

### PR DESCRIPTION
**Pull request by m-burst**
Ran and committed the contents of `./update.sh`

### CODE REVIEW

**Comment by rob93c** [comment]
Hi @m-burst and @keeganwitt, should we expect Docker images with Gradle 8.1 and Java 20 as part of this pull request?

**Comment by m-burst** [comment]
Hi @rob93c, as I can see in Gradle's changelog, version 8.1 supports building for Java 20 but not running on Java 20

**Comment by keeganwitt** [comment]
Thanks for the PR!

**Comment by keeganwitt** [comment]
Official images PR: https://github.com/docker-library/official-images/pull/14444

**Pull request merged**
