### PR TITLE
Add gradle 6.8

### PR DESCRIPTION
**Pull request by Sineaggi**

### CODE REVIEW

**Comment by keeganwitt** [comment]
Thanks for the PR. I never saw an announcement email for this.

**Comment by Sineaggi** [comment]
The search and replace I did failed. Looks like I accidentally retained the last b5ec091d 8 characters of 6.7.1's shasum, should be ```e2774e6fb77c43657decde25542dea710aafd78c4022d19b196e7e78d79d8c6c``` not ```e2774e6fb77c43657decde25542dea710aafd78c4022d19b196e7e78d79d8c6cb5ec091d```

**Comment by Sineaggi** [comment]
Fixed in #171, verified shasum is correct per https://services.gradle.org/distributions/gradle-6.8-bin.zip.sha256

**Comment by keeganwitt** [comment]
Official images PR: https://github.com/docker-library/official-images/pull/9408

**Pull request merged**
