### PR TITLE
Update Gradle to 4.7

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
I was not yet able to figure out what causes the version regex to fail. It seems to work locally.

**Comment by keeganwitt** [comment]
Thanks for the pull request!  I didn't have a chance yesterday to do the update.
The problem is they changed the output of `gradle --version`, so now grep finds more than one match.

```bash
$ docker run --rm -it gradle:4.7-alpine gradle --version | grep --extended-regexp "Gradle [0-9.]+"
Welcome to Gradle 4.7!
Gradle 4.7

$ docker run --rm -it gradle:4.6-alpine gradle --version | grep --extended-regexp "Gradle [0-9.]+"
Gradle 4.6
```

All we gotta do is change line 15 in _run.sh to
`version=$(docker run --user "${user}" --rm "${image}" gradle --version | grep  --extended-regexp "^Gradle [0-9.]+$" | grep  --extended-regexp --only-matching "[0-9.]+")`

**Comment by J0WI** [comment]
I was not able to reproduce the `Welcome` banner on my system. However, tests are happy with the new regex.

**Comment by keeganwitt** [comment]
Thanks!

**Pull request merged**
